Repository DavidBNeto/flor-de-lotus-api, pull requests merged in 2022-10, with the labels that each got.

#23 [New] README update
  README.md
  assets/arquitetura.jpg
  assets/homepage-docker-logo.png
  assets/mongodb_logo.jpg
  assets/nestjs_logo.png
  assets/node_npm _logo.png
  assets/prettier_logo.png
  assets/typescript-logo.png
Labels: documentation

#26 [Fix] fonte da imagem
  README.md
Labels: documentation

#28 Atualizando o README.md
  README.md
Labels: enhancement

#29 [Fix] Code Smells
  src/auth/auth.controller.ts
  src/auth/jwt.strategy.ts
  src/cultures/cultures.controller.ts
  src/cultures/cultures.service.ts
  src/cultures/models/cultures.model.ts
  src/hive/hive.controller.ts
  src/hive/hive.service.ts
  src/map/map.controller.ts
  src/map/map.service.ts
  src/map/models/map.model.ts
  src/plantation/models/plantation.model.ts
  src/plantation/plantation.controller.ts
  src/plantation/plantation.service.ts
  src/plants/model/plants.model.ts
  src/plants/plant.service.ts
  src/plants/plants.controller.ts
  src/seeders/seeder.ts
  src/user/user.controller.ts
  src/user/user.service.ts
Labels: bug, enhancement
